version: '3.7'

services:
  nakiseapi:
    container_name: nakiseapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8004:80"
    env_file:
      - ./.env
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
